#include <cstring>
#include <ostream>
#include <string>

#include "optiforge/backend/CodeGen.h"
#include "optiforge/backend/MachineIR.h"

namespace optiforge::backend {

namespace {

std::string hex64(std::uint64_t value) {
  static const char* kDigits = "0123456789abcdef";
  std::string out = "0x";
  for (int shift = 60; shift >= 0; shift -= 4) {
    out += kDigits[(value >> shift) & 0xf];
  }
  return out;
}

std::uint64_t bitsOf(double value) {
  std::uint64_t bits = 0;
  std::memcpy(&bits, &value, sizeof(bits));
  return bits;
}

std::string renderOperand(const MOperand& operand) {
  switch (operand.kind) {
    case MOperand::Kind::Reg:
      return std::string(regName(operand.reg));

    case MOperand::Kind::Imm:
      return "$" + std::to_string(operand.imm);

    case MOperand::Kind::Mem: {
      std::string out;
      if (operand.disp != 0) {
        out += std::to_string(operand.disp);
      }
      out += "(" + std::string(regName(operand.base)) + ")";
      return out;
    }

    case MOperand::Kind::Label:
      return operand.label;

    case MOperand::Kind::RipLabel:
      return operand.label + "(%rip)";
  }
  return "<?>";
}

/// Which operands of an instruction must be spelled as 8-bit registers.
///
/// `setcc` writes a single byte, so its only operand is 8-bit. `movzbq` widens
/// a byte into a quadword, so its *source* is 8-bit while its destination is
/// not -- naming both the same way is an operand-size mismatch the assembler
/// rejects.
bool operandIsByteSized(const char* mnemonic, std::size_t index) {
  if (std::strncmp(mnemonic, "set", 3) == 0) {
    return true;
  }
  if (std::strncmp(mnemonic, "movzb", 5) == 0) {
    return index == 0;
  }
  return false;
}

void printInstruction(const MInstr& instruction, std::ostream& out) {
  if (instruction.isLabel) {
    out << instruction.comment << ":\n";
    return;
  }

  std::string text = "\t";
  text += instruction.mnemonic;

  if (!instruction.operands.empty()) {
    // Pad so operand columns line up, which makes the output readable next to
    // objdump.
    while (text.size() < 12) {
      text += ' ';
    }
    for (std::size_t i = 0; i < instruction.operands.size(); ++i) {
      if (i != 0) {
        text += ", ";
      }
      const MOperand& operand = instruction.operands[i];
      if (operandIsByteSized(instruction.mnemonic, i) &&
          operand.kind == MOperand::Kind::Reg) {
        text += regName8(operand.reg);
      } else {
        text += renderOperand(operand);
      }
    }
  }

  out << text;
  if (!instruction.comment.empty()) {
    while (text.size() < 44) {
      text += ' ';
      out << ' ';
    }
    out << "# " << instruction.comment;
  }
  out << '\n';
}

}  // namespace

void printAssembly(const MModule& module, std::ostream& out) {
  out << "# Generated by OptiForge from \"" << module.sourceName << "\"\n";
  out << "# Target: x86-64 Windows (Microsoft x64 ABI)\n";
  out << "\t.text\n";

  for (const MFunction& function : module.functions) {
    out << '\n';
    out << "\t.globl\t" << function.name << '\n';
    // COFF symbol metadata; harmless if the linker does not need it.
    out << "\t.def\t" << function.name << ";\t.scl\t2;\t.type\t32;\t.endef\n";
    out << function.name << ":\n";

    for (const MBasicBlock& block : function.blocks) {
      out << block.label << ":\n";
      for (const MInstr& instruction : block.instructions) {
        printInstruction(instruction, out);
      }
    }
  }

  if (!module.floatConstants.empty() || module.needsNegateMask) {
    out << "\n\t.section\t.rdata,\"dr\"\n";

    if (module.needsNegateMask) {
      // xorpd reads 16 bytes and requires 16-byte alignment.
      out << "\t.align\t16\n";
      out << ".LCnegmask:\n";
      out << "\t.quad\t" << hex64(0x8000000000000000ULL) << "\n";
      out << "\t.quad\t0\n";
    }

    for (const FloatConstant& constant : module.floatConstants) {
      out << "\t.align\t8\n";
      out << constant.label << ":\n";
      // Emit the exact bit pattern: a decimal rendering would depend on the
      // assembler's float parsing and could round.
      out << "\t.quad\t" << hex64(bitsOf(constant.value)) << "\t# " << constant.value
          << "\n";
    }
  }
}

}  // namespace optiforge::backend
